// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUD62hQG2C2OEnhkqNuVDh-Zvv_b8efbE',
    appId: '1:900222786933:web:bc9469959edef225ce473c',
    messagingSenderId: '900222786933',
    projectId: 'draqi-cced3',
    authDomain: 'draqi-cced3.firebaseapp.com',
    storageBucket: 'draqi-cced3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxo8O_0pyF2PObCgGhngJx5VbnoL2a1FM',
    appId: '1:900222786933:android:e0adae13e1cfdbccce473c',
    messagingSenderId: '900222786933',
    projectId: 'draqi-cced3',
    storageBucket: 'draqi-cced3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPwcuUa-RAZP1Nm9px1RckK52xylBMyc',
    appId: '1:900222786933:ios:e934553f0ca96fd0ce473c',
    messagingSenderId: '900222786933',
    projectId: 'draqi-cced3',
    storageBucket: 'draqi-cced3.appspot.com',
    iosClientId: '900222786933-9hitp8m792ciic5vrp8l3oqueaveorjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.drAqi',
  );
}
